# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxdl6BZ4Fju9wyQ5tIZr5jxC6794cMtE
"""

def sistema_notas_turma():

  total_alunos = int(input("Quantos alunos existem na turma? "))



  for i in range(total_alunos):

    aluno_nome = input("Nome do aluno: ")

    n1 = float(input("Nota 1: "))

    n2 = float(input("Nota 2: "))



    media = (n1 + n2) / 2



    if media >= 7:

      print(aluno_nome, "Aprovado com média", media)

    elif media >= 5:

      print(aluno_nome, "Recuperação com média", media)

    else:

      print(aluno_nome, "Reprovado")