# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145wvFM2YYspkrPt9oiqwo355OrUFtOl3
"""

def analisar_clima():

  soma_temperaturas = 0

  dias_quentes = 0

  alerta_extremo = False



  for dia in range(7):

    temp = float(input("Digite a temperatura do dia: "))

    soma_temperaturas = soma_temperaturas + temp



    if temp > 35:

      dias_quentes = dias_quentes + 1



    if temp > 45 or temp < -5:

      alerta_extremo = True



  media = soma_temperaturas / 7



  print("Média semanal:", media)

  print("Dias acima de 35°C:", dias_quentes)



  if alerta_extremo == True:

    print("CUIDADO: Condições climáticas perigosas detectadas!")

  else:

    print("Clima dentro da normalidade operacional.")