# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blo8kLKVtOFr-GU0SgSzHGW7XDN9Jiwb
"""

def simulador_poupanca():

  saldo = float(input("Valor inicial do investimento: "))

  taxa = float(input("Taxa de juros mensal (%): "))

  meses = int(input("Número de meses: "))



  for i in range(meses):

    aporte = float(input("Depósito no mês: "))



    saldo = saldo + aporte

    juros = saldo * (taxa / 100)

    saldo = saldo + juros



    print("Saldo atual:", saldo)



    if saldo > 10000:

      print("Você atingiu 10 mil!")



  print("Saldo final:", saldo)