# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8t22jFhVZDJp1wR0KH8jnY-mrEkEhIn
"""

def processar_vendas():

  total_compra = 0

  itens_comprados = 0



  quantidade_tipos = int(input("Quantos produtos diferentes foram comprados? "))



  for i in range(quantidade_tipos):

    nome = input("Nome do produto: ")

    preco = float(input("Preço unitário: "))

    qtd = int(input("Quantidade deste produto: "))



    if preco <= 0 or qtd <= 0:

      print("Erro: Valores inválidos para", nome)

    else:

      subtotal = preco * qtd

      total_compra = total_compra + subtotal

      itens_comprados = itens_comprados + qtd



  if total_compra > 500:

    total_final = total_compra * 0.9

    print("Desconto de 10% aplicado!")

  elif total_compra > 200:

    total_final = total_compra * 0.95

  else:

    total_final = total_compra



  print("Resumo:", itens_comprados, "itens. Total a pagar: R$", total_final)