# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wh6ZwjT8PFWOjb2sTI2xGf0Zw5Z7IDla
"""

for item in biblioteca_musical["Toques"]: # nível 1

  for nome, matriz in item.items():   # nível 2



    transposta = []



    for i in range(len(matriz[0])):  # nível 3 (colunas)

      nova_linha = []



      for j in range(len(matriz)):  # percorre linhas

        nova_linha.append(matriz[j][i])



      transposta.append(nova_linha)



    item.update({nome: transposta})



print(biblioteca_musical)