# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHyrxWYLQLpBI3_57_zYrwL0u4PEbq8u
"""

import matplotlib.pyplot as plt



playlist = {

  "imagens": [

    {

      "nome": "Sorria!",

      "pixels": [

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]

      ]

    }

  ]

}



for imagem in playlist["imagens"]:

  for chave in imagem.keys():



    if chave == "pixels":

      nova_grade = []



      for linha in imagem[chave]:



        nova_linha = []



        for pixel in linha:



          if pixel == (255,255,0):

            novo = (

              pixel[0]//2,

              pixel[1]//2,

              pixel[2]//2

            )

          else:

            novo = pixel



          nova_linha.append(novo)



        nova_grade.append(nova_linha)



      imagem[chave] = nova_grade





for img in playlist["imagens"]:

  dados = img["pixels"]



  plt.imshow(dados)

  plt.title(img["nome"])

  plt.axis("off")

  plt.show()