# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMjvpUGQhDOgMBi9V2Yk-t8dLd9uF00R
"""

nova_grade = []



for chave, valor in emoji_data.items():

  if chave == "grade":

    for linha in valor: # nível 2

      nova_linha = []



      for pixel in linha: # nível 3

        if pixel == (255, 255, 0): # amarelo

          novo_pixel = (pixel[0]//2, pixel[1]//2, pixel[2]//2)

        else:

          novo_pixel = pixel



        nova_linha.append(novo_pixel)



      nova_grade.append(nova_linha)



emoji_data["grade"] = nova_grade



print(emoji_data)