# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7-MAhHP57J9R-9VNFiUmsxc0ANU2AJX
"""

def classificar_iqa(iqa):

  match iqa:

    case iqa if iqa <= 40:

      return "Boa"

    case iqa if iqa <= 80:

      return "Moderada"

    case iqa if iqa <= 120:

      return "Ruim"

    case _:

      return "Muito Ruim"





def calcular_conforto(temp, umidade, iqa):



  nota = 10



  nota -= abs(temp - 25) * 0.2



  if umidade < 30 or umidade > 80:

    nota -= 2



  if iqa > 80:

    nota -= 3

  elif iqa > 40:

    nota -= 1



  if nota < 0:

    nota = 0

  if nota > 10:

    nota = 10



  return round(nota, 2)





def analisar_microclima():



  dados_locais = [

    ["Praça Arborizada", [26, 65, 35], [24, 70, 30]],

    ["Cruzamento Movimentado", [30, 55, 90], [28, 60, 85]],

    ["Ponto de Ônibus", [32, 50, 70], [29, 55, 60]]

  ]



  for local in dados_locais:

    nome = local[0]

    print(f"\nLocal: {nome}")



    for i in range(1, len(local)):

      temp, umidade, iqa = local[i]



      classificacao = classificar_iqa(iqa)

      conforto = calcular_conforto(temp, umidade, iqa)



      print(f" Horário {i}:")

      print(f"  Temperatura: {temp}°C")

      print(f"  Umidade: {umidade}%")

      print(f"  IQA: {iqa} ({classificacao})")

      print(f"  Nota de Conforto: {conforto}")





analisar_microclima()