# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFP_KUTweJcrpXvgSoP1kXQM4AufmsJh
"""

def simulador_evacuacao():

  locais = ["Quarto", "Corredor", "Sala", "Cozinha", "Saída"]

  estados = ["chave", "livre", "porta_trancada", "livre", "saida"]



  posicao = 0

  inventario = []

  energia = 10 # limite de tentativas



  while energia > 0:

    print(f"\nVocê está em: {locais[posicao]}")

    estado_atual = estados[posicao]



    if estado_atual == "saida":

      print("Você conseguiu sair!")

      break



    if estado_atual == "chave":

      print("Você encontrou uma chave!")

      inventario.append("chave")

      posicao += 1



    elif estado_atual == "livre":

      print("Caminho livre.")

      posicao += 1



    elif estado_atual == "porta_trancada":

      print("Porta trancada!")



      if "chave" in inventario:

        print("Você usou a chave.")

        posicao += 1

      else:

        print("Sem chave! Voltando...")

        posicao -= 1



    if posicao < 0:

      posicao = 0

    if posicao >= len(locais):

      posicao = len(locais) - 1



    energia -= 1



  if energia == 0:

    print("Você ficou sem energia e não conseguiu sair.")



simulador_evacuacao()